# Generated by Django 6.0.2 on 2026-02-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordered_price',
            new_name='price',
        ),
    ]
